apiVersion: v1
kind: Pod 
metadata: 
  name: svc-pod 
  labels: 
    app: test
spec:
  containers:
    - name: test-co 
      image: mohumita/nodejsrepo
      ports:
        - containerPort: 
          protocol: TCP
              