apiVersion: v1
kind: Pod 
metadata: 
  name: svc-pod-2
  labels: 
    app: test-1
spec:
  containers:
    - name: test-co-1
      image: mohumita/dotnetrepo:dotnet_co
      ports:
        - containerPort: 5000
          protocol: TCP
              