apiVersion: v1
kind: Pod 
metadata: 
  name: svc-pod 
  labels: 
    app: test
spec:
  containers:
    - name: test-co 
      image: jenkins/jenkins:lts-jdk17
      ports:
        - containerPort: 8080
          protocol: TCP
              